### ISSUE TITLE
Bug: Main loop is not in main thread

### ISSUE THREAD

**Issue by NuMellow** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#104]
I get an error with the server if I refresh the data page a couple of times or generate several different graphs. The error says Main loop is not in main thread and it will repeat until I stop the server.
I think it has something to do with a warning when the server starts up which says: `generate_graphs.py:23: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.`

Does anyone else get this error/warning?

**Comment by BlastoiseBlue** [comment]
I've never gotten this error myself, however, I believe I remember @bpurbancic receiving an error like this. However, I would also recommend looking up this error, so that we can be certain both of what causes this issue, as well as how to fix it.

**Comment by rhayes13** [comment]
I have had the same error in the past and it would cause the server to crash, but recently I have not seen this.  If this is still an issue we need to do some detective work.

**Comment by bpurbancic** [comment]
Re-create this error as part of unit testing to know what needs to be resolved

**Comment by bpurbancic** [comment]
Through the exhaustive joint efforts of Ben and Chisulo (including learning where to hammer the single nail), this issue is now resolved!

**Comment by NuMellow** [comment]
**Recreating the bug:** (Before the fix)

Preconditions
-None needed

Steps
1. Run the server
2. Open data page, or display a graph if already on page
3. Observe that the terminal prints `datatitan_site\data\scripts\generate_graphs.py:35: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.`
4. Generate 5-6 different graphs. The graphs should be different to ensure caching is not used, however, type of chart, number of countries, and data type can be any combination.
5. After generating a few of these graphs, the page stops responding and the terminal infinitely prints out `RuntimeError: main thread is not in main loop` Until the server is stopped.
