### ISSUE TITLE
Create a multi-selection menu to choose multiple countries from a single menu

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#111]
By 10/12:
Create a multi-selection menu to choose multiple countries from a single menu (Emmet, Ben, Ryan)
Test: Check 3+ boxes for country selections and have chart display properly

**Comment by rhayes13** [comment]
It appears the multi-selection menu has been created. However the html formatting has been changed somewhere and I am not sure how to change it with the current implementation. This still needs to be fixed.
