### ISSUE TITLE
Test functionality of chosen web server to ensure compatibility with django and SQL pkg

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#114]
By 10/12

- [x] Review functionality of chosen web server to ensure compatibility with django and SQL pkg - alchemy? (Chisulo, Emmet, Brian)

- [x] Test: Have AWS successfully run webserver

Sub-tasks:

- [ ] Set up free EC2 instance and follow steps in Medium blog post: https://medium.com/@dikshitkathuria1803/hosting-a-django-website-on-aws-ec2-the-easy-way-3577ab4895d6 (Chisulo, Brian)

**Comment by sjiang1** [comment]
AWS successfully run webserver (including SQL pkg - alchemy?)

**Comment by bpurbancic** [comment]
Chisulo, Emmet, and I set up an EC2 instance on AWS and, after a bit of troubleshooting, got the empty blog page showing up on the web server.

![image](https://user-images.githubusercontent.com/55317460/95662920-7c6b9000-0b08-11eb-8d24-f5111ae3dd91.png)

**Comment by sjiang1** [comment]
The UI design is very professional. 🙌
