### ISSUE TITLE
Add search capability to speed country retrieval when 200 are available

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#129]
By 10/19

- [x] Add search capability to speed country retrieval when 200 are available (Jeff, Brian)

Test:

- [x] Type country name in search bar to filter the list

- [ ] Create unit test to confirm country choices are limited by search box typing, ie, in javascript (Brian)

**Comment by sjiang1** [comment]
Test: type country name in search bar, then the graph(?) shows the corresponding country?

**Comment by bpurbancic** [comment]
We now have all the countries listed and they can be found with the scroll bar; however, we do not yet have the capability to limit the countries by starting to type a name into a search box. We will move the due date for this forward one week.
