### ISSUE TITLE
Create charts (cases, deaths) for per capita numbers

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#133]
Is there an existing epic story we can associate this with or will it be added to a new one?

**Comment by NuMellow** [comment]
Is this due on Monday? if not we can make a new epic for it

**Comment by JeffPollack** [comment]
I think we can make this a new epic story. The current data seems to have everything we need to implement this. Looking into it now on the best way to display this.

**Comment by bpurbancic** [comment]
This task is taken care of with issue #110
