### ISSUE TITLE
Add custom scripts to AWS

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#140]
By 10/26:

- [x] Add custom scripts to AWS server to support full functionality of data page (Chisulo, Ben)

Test:

Other project team members test the page at 54.172.95.142:8000

**Comment by NuMellow** [comment]
The data page works now, however there is no data in the database meaning the graph functionality won't work.
We may need to switch from SQlite as AWS does not have the latest version available.
