### ISSUE TITLE
Need Pandas, Seaborn, and Matplotlib installed to the Python environment.

### ISSUE THREAD

**Issue by JeffPollack** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#34]
These are needed for graphs and need to be included in the installation instructions.

**Comment by bpurbancic** [comment]
I'm on it!

**Comment by BlastoiseBlue** [comment]
Make sure that you're using a Pipenv environment, as all of the requirements are in the Pipfile. That being said, I will add the required libraries to the requirements.txt file, but again, make sure you're using the Pipfile.
