### ISSUE TITLE
Seaborn data in temp directory

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#35]
Based on Slack convo, the code I used to test Seaborn data is in a temp directory. What's best practice to save things like this?

**Comment by JeffPollack** [comment]
I think saving it in a temp folder makes sense if we ever needed to look at original ideas. I can upload what I have for the CSV files later today when we meet.

**Comment by bpurbancic** [comment]
As a group, we decided to use the data/sourcedata directory for original downloads. We stored images in the temp directory.

**Comment by BlastoiseBlue** [comment]
The input csv file is actually in data/input

**Comment by bpurbancic** [comment]
Agreed, Emmet. I was referring to the original download before cleaning.
