### ISSUE TITLE
testplots.py runtime error: no module named 'inline'

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#47]
Jeff and Emmet:

Can one of you help me out with this? When I run Jeff's testplots.py code, I get the error above and a reference to line 5 which is the import inline statement.

Thanks!

**Comment by JeffPollack** [comment]
It is just a module you have to install. I do not believe I actually use it in this build, it was something that I had been messing with but did not end up utilizing. I will just comment it out for now.
