### ISSUE TITLE
Add seaborn script to views.py

### ISSUE THREAD

**Issue by NuMellow** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#50]
Views.py should be able to access the seaborn script to get the chart data to display on the html pages. 

- The html page will send a POST request with the country code and the type of chart to be displayed
- Views.py send the parameters to the seaborn script that will then prepare the chart to be displayed and return it to the views.py
- Views.py will then send the graph to the html page, which will be displayed

**Comment by BlastoiseBlue** [comment]
I have implemented the creation of a graph from the parameters sent to views.py, which will be returned as an HTML element that will be inserted into the data page.
