### ISSUE TITLE
Cleaning and sorting csv data

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#54]
Jeff and I are running into some data issues with the charts. For example, the top row in the USA data is the most recent date (9/12/2020) but subsequent rows start back at 12/31/2019 and go forward from there.

It looks like we need to sort the csv rows for each country by date either as part of the cleanup or programmatically within python.

Emmet, is this part of what you are working on in terms of the data cleanup?

**Comment by BlastoiseBlue** [comment]
The tables in the database will allow us to sort by multiple columns (specifically, I have it set to first sort by iso_code, then by date)
