### ISSUE TITLE
requirements.txt error: mysqlclient

### ISSUE THREAD

**Issue by bpurbancic** [COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans#98]
I'm still getting a mysqlclient error after installing requirments.txt. Can I still ignore it? Should we take it out of the requirements file? Or should I install MS Visual C++ 14.0?

![image](https://user-images.githubusercontent.com/55317460/95018061-1fb13680-062b-11eb-9889-312e98467b12.png)

**Comment by BlastoiseBlue** [comment]
I think we may be able to remove mysqlclient from the requirements.
